# Imagen base de Python
FROM python:3.9

WORKDIR /app

COPY . .

# Instalar las dependencias
RUN pip install Flask Flask-PyMongo Flask-Cors

EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]